Added Rolling Updates, updated Docs

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,10 +1,66 @@
 #!/bin/bash
-set -euf -o pipefail
 
-echo === Deploying AuriStorFS Special Resource ===
+SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
+APP_ROOT=$( cd $SCRIPTPATH/.. ; pwd -P )
 
-bin/createServiceAccount $@             # No-op if ServiceAccount already exists
+echo === Deploying AuriStorFS Special Resource into Namespace: $SPECIAL_RESOURCE_NAMESPACE ===
 
-bin/applyRBAC $@
-bin/deploySpecialResourceChart $@
-bin/deploySpecialResource $@
+$SCRIPTPATH/verifyEnvironment
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Invalid Environment Variables... exiting"
+       exit 1;
+fi
+
+
+oc get SpecialResource $SPECIAL_RESOURCE_NAME >/dev/null 2>/dev/null
+
+if [ $? -eq 0 ]; then
+       echo === "WARNING: Special Resource already exists: " $SPECIAL_RESOURCE_NAME
+       echo ======  Special Resource must first be removed via "'"undeploy"'" or "'"redeploy"'"
+       exit 1;
+fi
+
+CSI_DRIVER_FILE=$APP_ROOT/auristorfs-csi-driver.yaml 
+
+oc get CsiDriver auristorfs.csi.auristor.com >/dev/null 2>/dev/null
+
+if [ $? -ne 0 ]; then
+       echo === Creating AuriStor CSIDriver Object from file $CSI_DRIVER_FILE
+       oc create -f $CSI_DRIVER_FILE
+else
+       echo === CSI Driver Object already existed
+fi
+
+$SCRIPTPATH/addExtraPermissions
+
+$SCRIPTPATH/createServiceAccount
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: ServiceAccount creation failed ... exiting"
+       exit 1;
+fi
+
+echo === "Executing create maps command:" $SPECIAL_RESOURCE_CREATE_MAP_COMMAND
+$SPECIAL_RESOURCE_CREATE_MAP_COMMAND
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Map creation failed ... exiting"
+       exit 1;
+fi
+
+$SCRIPTPATH/buildSpecialResourceChart
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Special Resource Chart build failed... exiting"
+       exit 1;
+fi
+
+$SCRIPTPATH/deploySpecialResource
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Special Resource Deployment failed ... exiting"
+       exit 1;
+fi
+
+echo === Special Resource Deployed: $SPECIAL_RESOURCE_NAME
diff --git a/bin/redeploy b/bin/redeploy
--- a/bin/redeploy
+++ b/bin/redeploy
@@ -1,7 +1,24 @@
 #!/bin/bash
-set -euf -o pipefail
 
-echo == Performing a full delete, rebuild and deploy
+SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
+APP_ROOT=$( cd $SCRIPTPATH/.. ; pwd -P )
 
-bin/undeploy  $@
-bin/deploy    $@
+echo === Deleting and Restarting Special Resource
+
+$SCRIPTPATH/verifyEnvironment
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Invalid Environment Variables... exiting"
+       exit 1;
+fi
+
+$SCRIPTPATH/undeploy
+
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Undeploy Failed.  Will not attempt to redeploy"
+       exit 1;
+fi
+
+$SCRIPTPATH/deploy
+
+
diff --git a/bin/undeploy b/bin/undeploy
--- a/bin/undeploy
+++ b/bin/undeploy
@@ -1,13 +1,41 @@
 #!/bin/bash
 
-SPECIAL_RESOURCE_NAMESPACE=auristorfs-client
-
 SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
 
 echo === Undeploying Auristor Special Resource ===
 
-oc delete specialresource auristorfs-client --ignore-not-found=true
-oc delete cm -n $SPECIAL_RESOURCE_NAMESPACE auristorfs-client-chart --ignore-not-found=true
+$SCRIPTPATH/verifyEnvironment
 
-$SCRIPTPATH/unapplyRBAC
-exit 0
+if [ $? -ne 0 ]; then
+       echo === "ERROR: Invalid Environment Variables... exiting"
+       exit 1;
+fi
+
+oc get specialresource $SPECIAL_RESOURCE_NAME >/dev/null 2>/dev/null
+
+if [ $? -ne 0 ]; then
+       echo === Special Resource Not Found "'"$SPECIAL_RESOURCE_NAME"'"
+else
+    echo === Deleting Previous Special Resource: $SPECIAL_RESOURCE_NAME
+    oc delete specialresource $SPECIAL_RESOURCE_NAME 
+fi
+
+echo "=== Deleting Namespace and all SpecialResource supporting Namespace Objects:" $SPECIAL_RESOURCE_NAMESPACE
+oc delete namespace $SPECIAL_RESOURCE_NAMESPACE   2>/dev/null
+
+ if [ "$?" -ne 0 ]; then
+  echo === Namespace  "'"$SPECIAL_RESOURCE_NAMESPACE"'" not found, it probably was already deleted
+fi 
+
+echo === "Executing delete maps command:" $SPECIAL_RESOURCE_DELETE_MAP_COMMAND
+$SPECIAL_RESOURCE_DELETE_MAP_COMMAND
+
+$SCRIPTPATH/verifyPristine
+
+ if [ "$?" -ne 0 ]; then
+    echo === undepoy failed.  There are still remaining SpecialResource Objects
+    exit 1
+else
+    echo === SpecialResource: "'"$SPECIAL_RESOURCE_NAME"'" and SpecialResource namespace "'"$SPECIAL_RESOURCE_NAMESPACE"'" have been deleted
+    exit 0
+fi 
